export interface Coordinates {
	lat: number;
	lng: number;
}

export interface Tbi extends Coordinates {
	id: string;
	name: string;
	host: string;
	city: string;
	province: string;
	address: string;
	description?: string;
	url: string;
}

export const TBI_SOURCES = {
	program:
		"https://pcieerd.dost.gov.ph/work-with-us/technology-business-incubation-program/",
	heirit:
		"https://pcieerd.dost.gov.ph/wp-content/uploads/2025/11/2021_Programs_Projects_Beneficiaries_Implementation_Status.pdf",
	expansion:
		"https://pcieerd.dost.gov.ph/wp-content/uploads/2025/11/BAR1_4thqtr_2022.pdf",
	network:
		"https://region7.dost.gov.ph/dost-and-technology-business-incubators-in-the-ph-inks-agreement-for-tbi-4-0-program/",
	agriculture: "https://atbi.pcaarrd.dost.gov.ph/incubators",
	binhi:
		"https://wvsu.edu.ph/wvsu-dost-launch-innovation-projects-to-boost-science-and-technology-in-western-visayas/",
};

// Public DOST directories and project reports. Coordinates are approximate host
// campus locations, NOT surveyed incubator entrances. Do not imply live status or
// nationwide completeness; maintain source links when adding or updating records.
type Entry = [
	id: string,
	name: string,
	host: string,
	city: string,
	province: string,
	address: string,
	lat: number,
	lng: number,
	source: keyof typeof TBI_SOURCES,
	description?: string,
];
const ENTRIES: Entry[] = [
	[
		"upscale",
		"UPSCALE Innovation Hub",
		"University of the Philippines Diliman",
		"Quezon City",
		"Metro Manila",
		"National Engineering Center, UP Diliman",
		14.656,
		121.069,
		"network",
	],
	[
		"up-cebu",
		"UP Cebu Technology Business Incubator",
		"University of the Philippines Cebu",
		"Cebu City",
		"Cebu",
		"Gorordo Avenue, Lahug",
		10.322,
		123.898,
		"program",
		"Information and communication technology incubation.",
	],
	[
		"sibol",
		"SIBOL Labs",
		"University of the Philippines Los Baños",
		"Los Baños",
		"Laguna",
		"UPLB campus, College",
		14.165,
		121.241,
		"heirit",
		"Supports the commercialization of university research and startup ventures.",
	],
	[
		"aim",
		"AIM–Dado Banatao Incubator",
		"Asian Institute of Management",
		"Makati",
		"Metro Manila",
		"Paseo de Roxas, AIM campus",
		14.552,
		121.019,
		"network",
	],
	[
		"animo",
		"Animo Labs",
		"De La Salle University",
		"Manila",
		"Metro Manila",
		"2401 Taft Avenue, DLSU campus",
		14.565,
		120.993,
		"heirit",
	],
	[
		"navigatu",
		"Navigatú Technology Business Incubator",
		"Caraga State University",
		"Butuan",
		"Agusan del Norte",
		"Ampayon, CSU main campus",
		8.957,
		125.597,
		"network",
	],
	[
		"binhi",
		"BINHI Technology Business Incubator",
		"West Visayas State University",
		"Iloilo City",
		"Iloilo",
		"Luna Street, La Paz, WVSU campus",
		10.719,
		122.562,
		"binhi",
	],
	[
		"ideya",
		"IDEYA Technology Business Incubator",
		"Mindanao State University–Iligan Institute of Technology",
		"Iligan",
		"Lanao del Norte",
		"Andres Bonifacio Avenue, Tibanga",
		8.241,
		124.244,
		"network",
	],
	[
		"ustp",
		"USTP Technology Business Incubator",
		"University of Science and Technology of Southern Philippines",
		"Cagayan de Oro",
		"Misamis Oriental",
		"C.M. Recto Avenue, USTP campus",
		8.486,
		124.657,
		"network",
	],
	[
		"kite",
		"KITE Technology Business Incubator",
		"Batangas State University",
		"Batangas City",
		"Batangas",
		"Alangilan campus",
		13.785,
		121.074,
		"network",
	],
	[
		"palawan",
		"Palawan International Technology Business Incubator",
		"Palawan State University",
		"Puerto Princesa",
		"Palawan",
		"Tiniguiban, PSU main campus",
		9.775,
		118.731,
		"network",
	],
	[
		"baras",
		"BARAS Technology Business Incubator",
		"Bulacan State University",
		"Malolos",
		"Bulacan",
		"Guinhawa, BulSU main campus",
		14.858,
		120.815,
		"heirit",
	],
	[
		"kdra",
		"K'Drá 1905 Technology Business Incubator",
		"Iloilo Science and Technology University",
		"Iloilo City",
		"Iloilo",
		"Burgos Street, La Paz, ISAT U campus",
		10.711,
		122.569,
		"heirit",
	],
	[
		"umasenso",
		"UMasenso Technology Business Incubator",
		"University of Mindanao",
		"Davao City",
		"Davao del Sur",
		"Matina, UM campus",
		7.06,
		125.596,
		"heirit",
		"Technology business incubation for environmental solutions.",
	],
	[
		"uc",
		"University of the Cordilleras TBI",
		"University of the Cordilleras",
		"Baguio",
		"Benguet",
		"Governor Pack Road, UC campus",
		16.409,
		120.597,
		"heirit",
	],
	[
		"up-mindanao",
		"UP Mindanao Technology Business Incubator",
		"University of the Philippines Mindanao",
		"Davao City",
		"Davao del Sur",
		"Mintal, Tugbok, UP Mindanao campus",
		7.086,
		125.485,
		"heirit",
	],
	[
		"adunest",
		"AdU NEST Incubation Center",
		"Adamson University",
		"Manila",
		"Metro Manila",
		"900 San Marcelino Street",
		14.586,
		120.985,
		"heirit",
	],
	[
		"mapua",
		"Mapúa Technology Business Incubator",
		"Mapúa University",
		"Manila",
		"Metro Manila",
		"658 Muralla Street, Intramuros campus",
		14.59,
		120.978,
		"heirit",
	],
	[
		"hive",
		"HIVE Technology Business Incubator",
		"Technological University of the Philippines–Visayas",
		"Talisay",
		"Negros Occidental",
		"TUP Visayas campus",
		10.737,
		122.971,
		"heirit",
	],
	[
		"miriam",
		"Henry Sy, Sr. Innovation Center TBI",
		"Miriam College",
		"Quezon City",
		"Metro Manila",
		"Katipunan Avenue, Loyola Heights",
		14.651,
		121.078,
		"heirit",
	],
	[
		"hau",
		"Holy Angel University TBI",
		"Holy Angel University",
		"Angeles",
		"Pampanga",
		"Holy Angel Avenue, HAU campus",
		15.133,
		120.591,
		"heirit",
	],
	[
		"bicol",
		"Bicol University Technology Business Incubator",
		"Bicol University",
		"Legazpi",
		"Albay",
		"Rizal Street, BU main campus",
		13.145,
		123.713,
		"heirit",
	],
	[
		"slu",
		"SLU Technohub",
		"Saint Louis University",
		"Baguio",
		"Benguet",
		"A. Bonifacio Street, SLU main campus",
		16.419,
		120.596,
		"heirit",
	],
	[
		"tomasinno",
		"TOMASInno Center",
		"University of Santo Tomas",
		"Manila",
		"Metro Manila",
		"España Boulevard, UST campus",
		14.609,
		120.989,
		"heirit",
	],
	[
		"wildcat",
		"Wildcat Innovation Labs",
		"Cebu Institute of Technology University",
		"Cebu City",
		"Cebu",
		"N. Bacalso Avenue, CIT-U campus",
		10.294,
		123.881,
		"heirit",
	],
	[
		"silliman",
		"Silliman University Technology Business Incubator",
		"Silliman University",
		"Dumaguete",
		"Negros Oriental",
		"Hibbard Avenue, Silliman campus",
		9.313,
		123.306,
		"heirit",
	],
	[
		"sabatan",
		"SABATAN Technopreneurs Hub",
		"Nueva Vizcaya State University",
		"Bayombong",
		"Nueva Vizcaya",
		"NVSU Bayombong campus",
		16.487,
		121.149,
		"heirit",
	],
	[
		"samar",
		"Samar State University TBI",
		"Samar State University",
		"Catbalogan",
		"Samar",
		"Arteche Boulevard, SSU campus",
		11.775,
		124.886,
		"heirit",
	],
	[
		"agilab",
		"AGILab Technology Business Incubator",
		"University of Southeastern Philippines",
		"Davao City",
		"Davao del Sur",
		"Iñigo Street, Obrero, USeP campus",
		7.086,
		125.614,
		"heirit",
		"Incubation for Internet of Things and industrial technology applications.",
	],
	[
		"cagayan",
		"Business Incubation Zone for Novel and Sustainable Enterprises",
		"Cagayan State University",
		"Tuguegarao",
		"Cagayan",
		"Carig campus",
		17.658,
		121.752,
		"heirit",
	],
	[
		"silbi",
		"SILBI Technology Business Incubator",
		"University of the Philippines Baguio",
		"Baguio",
		"Benguet",
		"Governor Pack Road, UP Baguio campus",
		16.403,
		120.599,
		"expansion",
	],
	[
		"azul",
		"AZUL Hub",
		"Ateneo de Zamboanga University",
		"Zamboanga City",
		"Zamboanga del Sur",
		"La Purisima Street, AdZU campus",
		6.908,
		122.077,
		"expansion",
	],
	[
		"step-app",
		"STEP APP Technology Business Incubator",
		"Sultan Kudarat State University",
		"Tacurong",
		"Sultan Kudarat",
		"SKSU Tacurong campus",
		6.691,
		124.679,
		"expansion",
	],
	[
		"waves",
		"WAVES Technology Business Incubator",
		"Surigao del Norte State University",
		"Surigao City",
		"Surigao del Norte",
		"Narciso Street, SNSU campus",
		9.786,
		125.493,
		"expansion",
	],
	[
		"pwc",
		"Creative Hubs for Industry 4.0",
		"Philippine Women's College of Davao",
		"Davao City",
		"Davao del Sur",
		"University Avenue, Juna Subdivision, Matina",
		7.05,
		125.591,
		"expansion",
	],
	[
		"imetal",
		"I-METAL Technology Business Incubator",
		"Nueva Ecija University of Science and Technology",
		"Cabanatuan",
		"Nueva Ecija",
		"NEUST Sumacab campus",
		15.449,
		120.941,
		"expansion",
	],
	[
		"icebox",
		"ICEBOX Technology Business Incubator",
		"Mindanao State University",
		"General Santos",
		"South Cotabato",
		"MSU General Santos campus, Fatima",
		6.06,
		125.103,
		"expansion",
	],
	[
		"aslagan",
		"ASLAGAN Technology Business Incubator",
		"Tarlac State University",
		"Tarlac City",
		"Tarlac",
		"Romulo Boulevard, TSU campus",
		15.486,
		120.589,
		"expansion",
	],
	[
		"bannuar",
		"BANNUAR Technology Business Incubator",
		"Mariano Marcos State University",
		"Batac",
		"Ilocos Norte",
		"MMSU main campus",
		18.056,
		120.563,
		"expansion",
	],
	[
		"balik",
		"BALIK sa Bohol",
		"Bohol Island State University",
		"Tagbilaran",
		"Bohol",
		"C.P. Garcia Avenue, BISU main campus",
		9.649,
		123.856,
		"expansion",
	],
	[
		"blue-nest",
		"Ateneo Blue Nest",
		"Ateneo de Manila University",
		"Quezon City",
		"Metro Manila",
		"Katipunan Avenue, Loyola Heights campus",
		14.641,
		121.078,
		"expansion",
	],
	[
		"sikat",
		"SIKAT Technology Business Incubator",
		"Bataan Peninsula State University",
		"Balanga",
		"Bataan",
		"Capitol Drive, BPSU main campus",
		14.684,
		120.535,
		"expansion",
	],
];

// Agricultural TBIs are separate programs, even when a host also has a PCIEERD TBI.
const AGRICULTURAL: [string, string, string, string, string, number, number][] =
	[
		[
			"bpsu",
			"Bataan Peninsula State University",
			"Abucay",
			"Bataan",
			"BPSU Abucay campus",
			14.733,
			120.533,
		],
		[
			"bsu",
			"Benguet State University",
			"La Trinidad",
			"Benguet",
			"BSU main campus",
			16.453,
			120.591,
		],
		[
			"bu",
			"Bicol University",
			"Guinobatan",
			"Albay",
			"BU College of Agriculture and Forestry",
			13.188,
			123.598,
		],
		[
			"capsu",
			"Capiz State University",
			"Pontevedra",
			"Capiz",
			"CAPSU Pontevedra campus",
			11.432,
			122.835,
		],
		[
			"cvsu",
			"Cavite State University",
			"Indang",
			"Cavite",
			"CvSU main campus",
			14.196,
			120.879,
		],
		[
			"ctu",
			"Cebu Technological University",
			"Barili",
			"Cebu",
			"CTU Barili campus",
			10.133,
			123.534,
		],
		[
			"clsu",
			"Central Luzon State University",
			"Science City of Muñoz",
			"Nueva Ecija",
			"CLSU main campus",
			15.737,
			120.931,
		],
		[
			"cmu",
			"Central Mindanao University",
			"Maramag",
			"Bukidnon",
			"University Town, Musuan",
			7.858,
			125.051,
		],
		[
			"dmmmsu",
			"Don Mariano Marcos Memorial State University",
			"Bacnotan",
			"La Union",
			"DMMMSU North La Union campus",
			16.725,
			120.398,
		],
		[
			"fprdi",
			"Forest Products Research and Development Institute",
			"Los Baños",
			"Laguna",
			"DOST-FPRDI, College",
			14.159,
			121.234,
		],
		[
			"ifsu",
			"Ifugao State University",
			"Lamut",
			"Ifugao",
			"IFSU main campus",
			16.648,
			121.231,
		],
		[
			"isu",
			"Isabela State University",
			"Echague",
			"Isabela",
			"ISU main campus",
			16.723,
			121.681,
		],
		[
			"lspu",
			"Laguna State Polytechnic University",
			"Siniloan",
			"Laguna",
			"LSPU Siniloan campus",
			14.423,
			121.447,
		],
		[
			"mmsu",
			"Mariano Marcos State University",
			"Batac",
			"Ilocos Norte",
			"MMSU main campus",
			18.056,
			120.563,
		],
		[
			"psau",
			"Pampanga State Agricultural University",
			"Magalang",
			"Pampanga",
			"PSAU campus, San Agustin",
			15.222,
			120.694,
		],
		[
			"sksu",
			"Sultan Kudarat State University",
			"Isulan",
			"Sultan Kudarat",
			"SKSU campus",
			6.631,
			124.602,
		],
		[
			"usep",
			"University of Southeastern Philippines",
			"Tagum",
			"Davao del Norte",
			"USeP Tagum-Mabini campus",
			7.452,
			125.811,
		],
		[
			"usm",
			"University of Southern Mindanao",
			"Kabacan",
			"Cotabato",
			"USM main campus",
			7.119,
			124.837,
		],
		[
			"upv",
			"University of the Philippines Visayas",
			"Miagao",
			"Iloilo",
			"UP Visayas Miagao campus",
			10.642,
			122.236,
		],
		[
			"vsu",
			"Visayas State University",
			"Baybay",
			"Leyte",
			"Visca, VSU main campus",
			10.742,
			124.795,
		],
		[
			"wmsu",
			"Western Mindanao State University",
			"Zamboanga City",
			"Zamboanga del Sur",
			"WMSU main campus, Normal Road",
			6.914,
			122.061,
		],
		[
			"wpu",
			"Western Philippines University",
			"Aborlan",
			"Palawan",
			"WPU main campus",
			9.438,
			118.548,
		],
	];

export const TBIS: Tbi[] = [
	...ENTRIES.map(
		([
			id,
			name,
			host,
			city,
			province,
			address,
			lat,
			lng,
			source,
			description,
		]) => ({
			id,
			name,
			host,
			city,
			province,
			address,
			lat,
			lng,
			url: TBI_SOURCES[source],
			description,
		}),
	),
	...AGRICULTURAL.map(([id, host, city, province, address, lat, lng]) => ({
		id: `atbi-${id}`,
		name: `${host} Agri-Aqua TBI`,
		host,
		city,
		province,
		address,
		lat,
		lng,
		url: TBI_SOURCES.agriculture,
		description:
			"Agriculture and aquatic technology business incubation under the DOST-PCAARRD network.",
	})),
];

export function distanceKm(from: Coordinates, to: Coordinates): number {
	const radians = (value: number) => (value * Math.PI) / 180;
	const dLat = radians(to.lat - from.lat);
	const dLng = radians(to.lng - from.lng);
	const a =
		Math.sin(dLat / 2) ** 2 +
		Math.cos(radians(from.lat)) *
			Math.cos(radians(to.lat)) *
			Math.sin(dLng / 2) ** 2;
	return (
		6371.0088 * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - Math.min(1, a)))
	);
}

export function rankTbis(origin: Coordinates, tbis: readonly Tbi[] = TBIS) {
	return tbis
		.map((tbi) => ({ tbi, distance: distanceKm(origin, tbi) }))
		.sort((a, b) => a.distance - b.distance);
}

export function formatDistance(distance: number) {
	return distance < 1 ? "Less than 1 km" : `About ${Math.round(distance)} km`;
}
