/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as OnboardingRouteImport } from './routes/_onboarding'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SponsorRouteImport } from './routes/sponsor'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AppDiscoverRouteImport } from './routes/_app/discover'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as OnboardingBasicInfoRouteImport } from './routes/_onboarding/basic-info'
import { Route as OnboardingRoleSelectRouteImport } from './routes/_onboarding/role-select'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as SponsorHomeRouteImport } from './routes/sponsor/home'
import { Route as SponsorProfileRouteImport } from './routes/sponsor/profile'
import { Route as SponsorSubscriptionRouteImport } from './routes/sponsor/subscription'
import { Route as StudentHomeRouteImport } from './routes/student/home'
import { Route as StudentProfileRouteImport } from './routes/student/profile'
import { Route as StudentVaultsRouteImport } from './routes/student/vaults'
import { Route as AppGrantsIndexRouteImport } from './routes/_app/grants.index'
import { Route as AppGrantsGrantIdRouteImport } from './routes/_app/grants.$grantId'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects.$projectId'
import { Route as AppUUserIdRouteImport } from './routes/_app/u.$userId'
import { Route as StudentGrantsNewRouteImport } from './routes/student/grants/new'
import { Route as StudentProjectsIndexRouteImport } from './routes/student/projects/index'
import { Route as StudentProjectsNewRouteImport } from './routes/student/projects/new'
import { Route as StudentProjectsProjectIdIndexRouteImport } from './routes/student/projects/$projectId/index'
import { Route as StudentProjectsProjectIdEditRouteImport } from './routes/student/projects/$projectId/edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRoute = SponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingBasicInfoRoute = OnboardingBasicInfoRouteImport.update({
  id: '/basic-info',
  path: '/basic-info',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingRoleSelectRoute = OnboardingRoleSelectRouteImport.update({
  id: '/role-select',
  path: '/role-select',
  getParentRoute: () => OnboardingRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const SponsorHomeRoute = SponsorHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => SponsorRoute,
} as any)
const SponsorProfileRoute = SponsorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SponsorRoute,
} as any)
const SponsorSubscriptionRoute = SponsorSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => SponsorRoute,
} as any)
const StudentHomeRoute = StudentHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentVaultsRoute = StudentVaultsRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => StudentRoute,
} as any)
const AppGrantsIndexRoute = AppGrantsIndexRouteImport.update({
  id: '/grants/',
  path: '/grants/',
  getParentRoute: () => AppRoute,
} as any)
const AppGrantsGrantIdRoute = AppGrantsGrantIdRouteImport.update({
  id: '/grants/$grantId',
  path: '/grants/$grantId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppUUserIdRoute = AppUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => AppRoute,
} as any)
const StudentGrantsNewRoute = StudentGrantsNewRouteImport.update({
  id: '/grants/new',
  path: '/grants/new',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProjectsIndexRoute = StudentProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProjectsNewRoute = StudentProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProjectsProjectIdIndexRoute =
  StudentProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentProjectsProjectIdEditRoute =
  StudentProjectsProjectIdEditRouteImport.update({
    id: '/projects/$projectId/edit',
    path: '/projects/$projectId/edit',
    getParentRoute: () => StudentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/sponsor': typeof SponsorRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/discover': typeof AppDiscoverRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/basic-info': typeof OnboardingBasicInfoRoute
  '/role-select': typeof OnboardingRoleSelectRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/sponsor/home': typeof SponsorHomeRoute
  '/sponsor/profile': typeof SponsorProfileRoute
  '/sponsor/subscription': typeof SponsorSubscriptionRoute
  '/student/home': typeof StudentHomeRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/vaults': typeof StudentVaultsRoute
  '/grants/$grantId': typeof AppGrantsGrantIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/u/$userId': typeof AppUUserIdRoute
  '/student/grants/new': typeof StudentGrantsNewRoute
  '/student/projects/new': typeof StudentProjectsNewRoute
  '/grants/': typeof AppGrantsIndexRoute
  '/student/projects/': typeof StudentProjectsIndexRoute
  '/student/projects/$projectId/edit': typeof StudentProjectsProjectIdEditRoute
  '/student/projects/$projectId/': typeof StudentProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/sponsor': typeof SponsorRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/discover': typeof AppDiscoverRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/basic-info': typeof OnboardingBasicInfoRoute
  '/role-select': typeof OnboardingRoleSelectRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/sponsor/home': typeof SponsorHomeRoute
  '/sponsor/profile': typeof SponsorProfileRoute
  '/sponsor/subscription': typeof SponsorSubscriptionRoute
  '/student/home': typeof StudentHomeRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/vaults': typeof StudentVaultsRoute
  '/grants/$grantId': typeof AppGrantsGrantIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/u/$userId': typeof AppUUserIdRoute
  '/student/grants/new': typeof StudentGrantsNewRoute
  '/student/projects/new': typeof StudentProjectsNewRoute
  '/grants': typeof AppGrantsIndexRoute
  '/student/projects': typeof StudentProjectsIndexRoute
  '/student/projects/$projectId/edit': typeof StudentProjectsProjectIdEditRoute
  '/student/projects/$projectId': typeof StudentProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_onboarding': typeof OnboardingRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/sponsor': typeof SponsorRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_onboarding/basic-info': typeof OnboardingBasicInfoRoute
  '/_onboarding/role-select': typeof OnboardingRoleSelectRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/sponsor/home': typeof SponsorHomeRoute
  '/sponsor/profile': typeof SponsorProfileRoute
  '/sponsor/subscription': typeof SponsorSubscriptionRoute
  '/student/home': typeof StudentHomeRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/vaults': typeof StudentVaultsRoute
  '/_public/': typeof PublicIndexRoute
  '/_app/grants/$grantId': typeof AppGrantsGrantIdRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/u/$userId': typeof AppUUserIdRoute
  '/student/grants/new': typeof StudentGrantsNewRoute
  '/student/projects/new': typeof StudentProjectsNewRoute
  '/_app/grants/': typeof AppGrantsIndexRoute
  '/student/projects/': typeof StudentProjectsIndexRoute
  '/student/projects/$projectId/edit': typeof StudentProjectsProjectIdEditRoute
  '/student/projects/$projectId/': typeof StudentProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sponsor'
    | '/student'
    | '/discover'
    | '/notifications'
    | '/settings'
    | '/basic-info'
    | '/role-select'
    | '/admin/dashboard'
    | '/sponsor/home'
    | '/sponsor/profile'
    | '/sponsor/subscription'
    | '/student/home'
    | '/student/profile'
    | '/student/vaults'
    | '/grants/$grantId'
    | '/projects/$projectId'
    | '/u/$userId'
    | '/student/grants/new'
    | '/student/projects/new'
    | '/grants/'
    | '/student/projects/'
    | '/student/projects/$projectId/edit'
    | '/student/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/sponsor'
    | '/student'
    | '/discover'
    | '/notifications'
    | '/settings'
    | '/basic-info'
    | '/role-select'
    | '/admin/dashboard'
    | '/sponsor/home'
    | '/sponsor/profile'
    | '/sponsor/subscription'
    | '/student/home'
    | '/student/profile'
    | '/student/vaults'
    | '/grants/$grantId'
    | '/projects/$projectId'
    | '/u/$userId'
    | '/student/grants/new'
    | '/student/projects/new'
    | '/grants'
    | '/student/projects'
    | '/student/projects/$projectId/edit'
    | '/student/projects/$projectId'
  id:
    | '__root__'
    | '/_app'
    | '/_onboarding'
    | '/_public'
    | '/admin'
    | '/sponsor'
    | '/student'
    | '/_app/discover'
    | '/_app/notifications'
    | '/_app/settings'
    | '/_onboarding/basic-info'
    | '/_onboarding/role-select'
    | '/admin/dashboard'
    | '/sponsor/home'
    | '/sponsor/profile'
    | '/sponsor/subscription'
    | '/student/home'
    | '/student/profile'
    | '/student/vaults'
    | '/_public/'
    | '/_app/grants/$grantId'
    | '/_app/projects/$projectId'
    | '/_app/u/$userId'
    | '/student/grants/new'
    | '/student/projects/new'
    | '/_app/grants/'
    | '/student/projects/'
    | '/student/projects/$projectId/edit'
    | '/student/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  SponsorRoute: typeof SponsorRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor': {
      id: '/sponsor'
      path: '/sponsor'
      fullPath: '/sponsor'
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_onboarding/basic-info': {
      id: '/_onboarding/basic-info'
      path: '/basic-info'
      fullPath: '/basic-info'
      preLoaderRoute: typeof OnboardingBasicInfoRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/role-select': {
      id: '/_onboarding/role-select'
      path: '/role-select'
      fullPath: '/role-select'
      preLoaderRoute: typeof OnboardingRoleSelectRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sponsor/home': {
      id: '/sponsor/home'
      path: '/home'
      fullPath: '/sponsor/home'
      preLoaderRoute: typeof SponsorHomeRouteImport
      parentRoute: typeof SponsorRoute
    }
    '/sponsor/profile': {
      id: '/sponsor/profile'
      path: '/profile'
      fullPath: '/sponsor/profile'
      preLoaderRoute: typeof SponsorProfileRouteImport
      parentRoute: typeof SponsorRoute
    }
    '/sponsor/subscription': {
      id: '/sponsor/subscription'
      path: '/subscription'
      fullPath: '/sponsor/subscription'
      preLoaderRoute: typeof SponsorSubscriptionRouteImport
      parentRoute: typeof SponsorRoute
    }
    '/student/home': {
      id: '/student/home'
      path: '/home'
      fullPath: '/student/home'
      preLoaderRoute: typeof StudentHomeRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/vaults': {
      id: '/student/vaults'
      path: '/vaults'
      fullPath: '/student/vaults'
      preLoaderRoute: typeof StudentVaultsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_app/grants/': {
      id: '/_app/grants/'
      path: '/grants'
      fullPath: '/grants/'
      preLoaderRoute: typeof AppGrantsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grants/$grantId': {
      id: '/_app/grants/$grantId'
      path: '/grants/$grantId'
      fullPath: '/grants/$grantId'
      preLoaderRoute: typeof AppGrantsGrantIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/u/$userId': {
      id: '/_app/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof AppUUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/student/grants/new': {
      id: '/student/grants/new'
      path: '/grants/new'
      fullPath: '/student/grants/new'
      preLoaderRoute: typeof StudentGrantsNewRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/projects/': {
      id: '/student/projects/'
      path: '/projects'
      fullPath: '/student/projects/'
      preLoaderRoute: typeof StudentProjectsIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/projects/new': {
      id: '/student/projects/new'
      path: '/projects/new'
      fullPath: '/student/projects/new'
      preLoaderRoute: typeof StudentProjectsNewRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/projects/$projectId/': {
      id: '/student/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/student/projects/$projectId/'
      preLoaderRoute: typeof StudentProjectsProjectIdIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/projects/$projectId/edit': {
      id: '/student/projects/$projectId/edit'
      path: '/projects/$projectId/edit'
      fullPath: '/student/projects/$projectId/edit'
      preLoaderRoute: typeof StudentProjectsProjectIdEditRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface AppRouteChildren {
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppGrantsGrantIdRoute: typeof AppGrantsGrantIdRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppUUserIdRoute: typeof AppUUserIdRoute
  AppGrantsIndexRoute: typeof AppGrantsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDiscoverRoute: AppDiscoverRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppGrantsGrantIdRoute: AppGrantsGrantIdRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppUUserIdRoute: AppUUserIdRoute,
  AppGrantsIndexRoute: AppGrantsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingBasicInfoRoute: typeof OnboardingBasicInfoRoute
  OnboardingRoleSelectRoute: typeof OnboardingRoleSelectRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingBasicInfoRoute: OnboardingBasicInfoRoute,
  OnboardingRoleSelectRoute: OnboardingRoleSelectRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SponsorRouteChildren {
  SponsorHomeRoute: typeof SponsorHomeRoute
  SponsorProfileRoute: typeof SponsorProfileRoute
  SponsorSubscriptionRoute: typeof SponsorSubscriptionRoute
}

const SponsorRouteChildren: SponsorRouteChildren = {
  SponsorHomeRoute: SponsorHomeRoute,
  SponsorProfileRoute: SponsorProfileRoute,
  SponsorSubscriptionRoute: SponsorSubscriptionRoute,
}

const SponsorRouteWithChildren =
  SponsorRoute._addFileChildren(SponsorRouteChildren)

interface StudentRouteChildren {
  StudentHomeRoute: typeof StudentHomeRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentVaultsRoute: typeof StudentVaultsRoute
  StudentGrantsNewRoute: typeof StudentGrantsNewRoute
  StudentProjectsNewRoute: typeof StudentProjectsNewRoute
  StudentProjectsIndexRoute: typeof StudentProjectsIndexRoute
  StudentProjectsProjectIdEditRoute: typeof StudentProjectsProjectIdEditRoute
  StudentProjectsProjectIdIndexRoute: typeof StudentProjectsProjectIdIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentHomeRoute: StudentHomeRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentVaultsRoute: StudentVaultsRoute,
  StudentGrantsNewRoute: StudentGrantsNewRoute,
  StudentProjectsNewRoute: StudentProjectsNewRoute,
  StudentProjectsIndexRoute: StudentProjectsIndexRoute,
  StudentProjectsProjectIdEditRoute: StudentProjectsProjectIdEditRoute,
  StudentProjectsProjectIdIndexRoute: StudentProjectsProjectIdIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  SponsorRoute: SponsorRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
